resources:
  - 10-ingress-nginx-namespace.yaml

namespace: ingress-nginx

helmCharts:
  - releaseName: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: 4.13.3
    valuesFile: values.yaml
    skipTests: true
