apiVersion: v1
kind: Service
metadata:
  labels:
    tier: application
      #    env: dev
  name: nginx-deployment
  namespace: nginx-website

spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    run: nginx
      #    env: dev
  type: LoadBalancer
  loadBalancerIP: 10.10.20.231